---
name: Template-Plugin-StripComments
version: 1.00
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: TT filter to strip comment blocks
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template: 2
build_requires:
  Test::More: 0
provides:
  Template::Plugin::StripComments:
    file: lib/Template/Plugin/StripComments.pm
    version: 1.00
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
